version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  consul:
    image: hashicorp/consul
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"       # Web UI
      - "8600:8600/udp"   # DNS interface
    volumes:
      - consul_data:/consul/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Ensure you have a prometheus.yml config file in the same directory as this docker-compose file.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"   # Change the admin password as needed.
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pgdata:
  consul_data:
  grafana_data:
